SELECT ROWNUM AS rownumber FROM FAVORIT WHERE MEM_ID = 'a001';
DELETE  FROM FAVORIT
 WHERE STOCK_NO = ( SELECT A.STOCK_NO
           FROM (SELECT ROWNUM AS rownumber, STOCK_NO FROM FAVORIT WHERE MEM_ID = 'b001') A
           WHERE A.rownumber = 2);
COMMIT;


-- 인덱스로 해당 종목 정보 가져오기
SELECT STOCK_NO, 
       CUR_PRICE
  FROM (SELECT A.STOCK_NO AS BNO
          FROM (SELECT STOCK_NO, ROWNUM AS rownumber FROM KOSPY) A
         WHERE A.rownumber = 4) B, STOCK C
 WHERE B.BNO = C.STOCK_NO;
 
-- 아이디,인덱스로 즐겨찾기 목록에 있는 종목 상세정보 가져오기
SELECT A.STOCK_NO
  FROM (SELECT STOCK_NO, ROWNUM AS rownumber FROM FAVORIT WHERE MEM_ID = 'a001' ORDER BY STOCK_NO) A
 WHERE A.rownumber = 1
 
 SELECT C.STOCK_NAME,
        C.STOCK_NO,
        C.CUR_PRICE
   FROM (SELECT A.STOCK_NO AS BNO
           FROM (SELECT STOCK_NO, ROWNUM AS rownumber FROM FAVORIT WHERE MEM_ID = 'a001' ORDER BY STOCK_NO DESC) A
          WHERE A.rownumber = 1)B, STOCK C
  WHERE B.BNO = C.STOCK_NO;

DELETE FROM FAVORIT;
COMMIT;

UPDATE MEMBER
   SET MY_MONEY = MY_MONEY + 1000
   WHERE MEM_ID = 'b001';
   
DELETE FROM FAVORIT;
DELETE FROM MEMBER;
COMMIT;

INSERT INTO BUY_STOCK
    VALUES(
    (SELECT NVL(MAX(BUY_NO), 0)+ 1 FROM BUY_STOCK),
    
    )
    
SELECT STOCK_NO, 
       CUR_PRICE
  FROM (SELECT A.STOCK_NO AS BNO
          FROM (SELECT STOCK_NO, ROWNUM AS rownumber FROM KOSPY) A
         WHERE A.rownumber = 4) B, STOCK C
 WHERE B.BNO = C.STOCK_NO;
 
 UPDATE MEMBER
    SET MY_MONEY = MY_MONEY - 100000
WHERE MEM_ID = 'a001';

COMMIT;

-- MYMONEY UPDATE
CREATE OR REPLACE TRIGGER TG_UPDATE_MONEY
    AFTER INSERT ON BUY_STOCK
    FOR EACH ROW
BEGIN
    UPDATE MEMBER
       SET MY_MONEY = MY_MONEY - (:NEW.BUY_PRICE * :NEW.STOCK_QTY)
     WHERE MEM_ID = :NEW.MEM_ID;
END;

DROP TRIGGER TG_UPDATE_MONEY;

COMMIT;

INSERT INTO BUY_STOCK
				 VALUES(
				(SELECT NVL(MAX(BUY_NO), 0)+ 1 FROM BUY_STOCK)
				,100000,4,'K101','a001', SYSDATE
				);
                
create or replace TRIGGER TG_UPDATE_MONEY
    AFTER INSERT ON BUY_STOCK
    FOR EACH ROW
BEGIN
    UPDATE MEMBER
       SET MY_MONEY = MY_MONEY - (:NEW.BUY_PRICE * :NEW.STOCK_QTY)
     WHERE MEM_ID = :NEW.MEM_ID;
END;

DELETE FROM BUY_STOCK;
COMMIT;